// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fylycylmrahapizfzebd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5bHljeWxtcmFoYXBpemZ6ZWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDAyNDQsImV4cCI6MjA3NDAxNjI0NH0.7ZqyQzbl1JYv3g_-saG8Ts7d0BTHHguLSiFSZjeby4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});